name: ui_bloom
description: A Flutter library for beautiful, ready-to-use UI components like BloomButton and more. ğŸŒ¸
version: 1.0.0
homepage: https://github.com/saifAlimohamed/
repository: https://github.com/saifAlimohamed/ui_bloom.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter  # Ø¶Ø±ÙˆØ±ÙŠ Ù„Ù…ÙƒØªØ¨Ø§Øª Flutter

dev_dependencies:
  lints: ^5.0.0    # Ù„Ø¥Ø¬Ø±Ø§Ø¡Ø§Øª Ø§Ù„ØªØ­Ù„ÙŠÙ„ (analysis)
  test: ^1.24.0    # Ù„Ù„Ø§Ø®ØªØ¨Ø§Ø±Ø§Øª
  flutter_test:     # Ø§Ø®ØªØ¨Ø§Ø±Ø§Øª Flutter (ÙŠØ¶Ø§Ù ØªÙ„Ù‚Ø§Ø¦ÙŠÙ‹Ø§ Ù…Ø¹ Flutter)
    sdk: flutter